apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: gcp-apache-subscription
  namespace: gcp-apache-test
  labels:
    cloud: Google
  annotations:
    apps.open-cluster-management.io/github-path: kustomize-app
spec:
  channel: gcp-apache-test/apache-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: gcp-clusters
